version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddemdb

    ports:
      - "3307:3306"  # Map MySQL port to host
    
    networks:
      - app-network


  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.33.11:3307/kaddemdb  # Use service name for connection
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
