version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kaddemdb
    ports:
      - "3307:3306"
    volumes:
      - dbs:/var/lib/mysql

  app-timesheet:
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile  
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/kaddemdb",
        "spring.datasource.username": "root",
        "spring.datasource.password": null,
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysqldb
    environment:
      - PMA_HOST=mysqldb
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8099:80"

volumes:
  dbs:
