version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: kaddemdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.33.11:3307/kaddemdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
